# Generated by Django 3.1.4 on 2020-12-31 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=20)),
                ('currency', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
