# Generated by Django 3.1.4 on 2020-12-31 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='data',
        ),
        migrations.AddField(
            model_name='currency',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
