# Generated by Django 3.1.4 on 2020-12-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20201231_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='base_currency',
            new_name='base',
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(max_length=20),
        ),
    ]
